{{- if .Values.devspaces.enabled }}
{{- $existingSub := lookup "operators.coreos.com/v1alpha1" "Subscription" .Values.devspaces.namespace .Values.devspaces.name }}
{{- if not $existingSub.metadata }}
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: {{ .Values.devspaces.name }}
  namespace: {{ .Values.devspaces.namespace }}
  labels:
    demo.redhat.com/application: "devspaces"
spec:
  channel: {{ .Values.devspaces.channel }}
  installPlanApproval: {{ .Values.devspaces.installPlanApproval }}
  name: {{ .Values.devspaces.name }}
  source: {{ .Values.devspaces.source }}
  sourceNamespace: {{ .Values.devspaces.sourceNamespace }}
{{- end }}
{{- end }}
