{{- if .Values.secrets.enabled }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secrets.name }}
  namespace: {{ .Values.secrets.namespace }}
  labels:
    demo.redhat.com/application: "field-content"
  annotations:
    argocd.argoproj.io/sync-wave: "1"
type: {{ .Values.secrets.type }}
data:
  OPENAI_API_KEY: {{ .Values.litemaas.apiKey | b64enc | quote }}
  OPENAI_API_BASE: {{ .Values.litemaas.apiUrl | b64enc | quote }}
{{- end }}
