{{- if .Values.rhbk-operator.enabled }}
{{- $existingSub := lookup "operators.coreos.com/v1alpha1" "Subscription" .Values.rhbk-operator.namespace .Values.rhbk-operator.name }}
{{- if not $existingSub.metadata }}
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: {{ .Values.rhbk-operator.name }}
  namespace: {{ .Values.rhbk-operator.namespace }}
  labels:
    demo.redhat.com/application: "rhbk-operator"
spec:
  channel: {{ .Values.rhbk-operator.channel }}
  installPlanApproval: {{ .Values.rhbk-operator.installPlanApproval }}
  name: {{ .Values.rhbk-operator.name }}
  source: {{ .Values.rhbk-operator.source }}
  sourceNamespace: {{ .Values.rhbk-operator.sourceNamespace }}
{{- end }}
{{- end }}
