mta-operator:
  enabled: true
  name: mta-operator
  namespace: openshift-mta
  channel: stable-v8.0
  source: redhat-operators
  sourceNamespace: openshift-marketplace
  installPlanApproval: Automatic